RaiderIO/keystone.guru

database/seeds/DungeonsSeeder.php

Hopefully last pull request for release :)

Enemy forces weren't being applied properly, causing database issue.

---

app/Http/Controllers/APIDungeonRouteController.php
app/Models/DungeonRoute.php
resources/views/dungeonroute/view.blade.php

Fix: You can rate your own routes

---

resources/assets/css/custom.css

Fixed some CSS issues I found on staging.

---

resources/views/misc/changelog.blade.php

Forgot to update the changelog

Updated changelog.

---

resources/assets/js/custom/inline/dungeonroute/table.js
resources/assets/js/custom/inline/dungeonroute/tableview.js
resources/assets/js/custom/inline/inlinemanager.js
resources/assets/js/custom/inline/team/edit.js
resources/lang/en/js.php
resources/views/common/dungeonroute/table.blade.php
resources/views/common/general/inline.blade.php
resources/views/team/invite.blade.php

Team logo is now properly displayed when inviting people to your team
Moderator controls are no longer displayed to non-moderators in routes, members section.

#77 Fixed multiple issues.

---

app/Http/Controllers/APIDungeonRouteController.php
database/seeds/releases/v3.0.6.json
resources/assets/js/custom/dungeonfloorswitchmarker.js
resources/assets/js/custom/dungeonmap.js
resources/assets/js/custom/inline/common/group/composition.js
resources/assets/js/custom/inline/common/maps/killzonessidebar.js
resources/assets/js/custom/inline/layouts/app.js
resources/assets/js/custom/killzone.js
resources/assets/js/custom/mapobject.js
resources/assets/js/custom/mapobjectgroup.js
resources/assets/js/custom/mapobjectgroups/enemymapobjectgroup.js
resources/assets/js/custom/mapobjectgroups/killzonemapobjectgroup.js
resources/assets/js/custom/mapstate/addkillzonemapstate.js
resources/assets/js/custom/mapstate/enemyselection/enemyselection.js
resources/assets/js/custom/mapstate/mapobjectmapstate.js
resources/assets/js/custom/signalable.js
resources/assets/js/custom/statemanager.js
resources/assets/js/handlebars/map_enemy_visuals_template.handlebars
resources/assets/js/handlebars/release_copy_to_discord.handlebars
resources/assets/js/handlebars/release_copy_to_github.handlebars
resources/assets/js/handlebars/release_copy_to_reddit.handlebars
resources/views/common/general/statemanager.blade.php
resources/views/common/group/composition.blade.php
resources/views/common/maps/map.blade.php
resources/views/dungeonroute/edit.blade.php
webpack.mix.js

Map changes:
* #323 Pull indices are now visible on all pulls to help identification.
* #330 Pulls are now loaded once instead of every time you switch a floor. Fixed various issues when switching floors. Increased general performance.

Release v3.0.6

---

app/Logic/MDT/IO/ImportString.php

Created our own pull index counter so there are no longer visually skipped pulls (only increment counter if enemy count > 0)

added separate pull index counter

---

docs/tutorials/contribution/setting_up_local_development_clean.md

Modified/clarified a few of the instructions

updated local dev setup file

---

app/Http/Controllers/AdminToolsController.php
app/Logic/MDT/Conversion.php
app/Logic/MDT/IO/ImportString.php
app/Models/DungeonRoute.php
app/Models/DungeonRouteAttribute.php
app/Models/DungeonRoutePlayerClass.php
app/Models/DungeonRoutePlayerRace.php
app/Models/DungeonRoutePlayerSpecialization.php
database/seeders/releases/v4.4.1.json
resources/assets/js/custom/inline/common/maps/editsidebar/settingstabroute.js
resources/views/common/dungeonroute/card.blade.php
storage/framework/cache/.gitignore

MDT importer changes:
* #940 Fixed various issues with the MDT string importer.

Release v4.4.1 - Bugfixes for MDT importer

---

app/Logic/SimulationCraft/RaidEventPullEnemy.php
app/Logic/SimulationCraft/RaidEventsCollection.php
app/Models/Patreon/PatreonBenefit.php
app/Models/Patreon/PatreonUserBenefit.php
app/Models/SimulationCraft/SimulationCraftRaidEventsOptions.php
database/migrations/2022_09_19_142954_add_nullable_to_user_id_column_in_simulation_craft_raid_events_options_table.php
database/seeders/releases/v5.0.1.json
database/seeders/releases/v5.0.json
resources/assets/js/custom/admin/adminmountablearea.js
resources/views/layouts/sitepage.blade.php
tests/Unit/App/Logic/SimulationCraft/RaidEventPullEnemyTest.php

Bugfixes:
* #1376 Fixed various issues with the SimulationCraft implementation which brings it much closer to actual log results (thanks Finalslave for reporting).

Release v5.0.1

---

app/Http/Controllers/APIMapIconController.php
app/Http/Controllers/APIMappingModelBaseController.php
app/Http/Controllers/APIProfileController.php
app/Service/MDT/MDTExportStringService.php
app/Service/Patreon/Logging/PatreonApiServiceLogging.php
app/Service/Patreon/Logging/PatreonApiServiceLoggingInterface.php
app/Service/Patreon/PatreonApiService.php
database/migrations/2023_03_13_210906_update_locale_column_default_in_users_table.php
database/migrations/2023_03_13_211006_fix_incorrect_locale_column_in_users_table.php
database/migrations/2023_03_14_221618_update_mapping_version_id_in_map_icons_table.php
database/seeders/DungeonDataSeeder.php
database/seeders/releases/v6.3.1.json
resources/assets/js/custom/mapobjectgroups/killzonemapobjectgroup.js
resources/views/dungeonroute/preview.blade.php
resources/views/profile/edittabs/profile.blade.php

Bugfixes:
* #1532 Deleting a pull will now once again properly re-arrange the indices of your remaining pulls and not leave you with gaps or unordered pulls.
* #1628 Color selection in your profile no longer has a messed up layout since the addition of the Evoker class (class colors are liinked there).
* #1629 Newly registered users no longer have an unknown locale selected.
* #1631 Adding new map icons to any route no longer has them showing up in other routes.

Release v6.3.1 - Hotfix for map icons showing up in routes they don't belong to

---

app/Http/Middleware/DebugBarMessageLogger.php
app/Providers/KeystoneGuruServiceProvider.php
app/Service/GameVersion/GameVersionService.php
database/seeders/releases/v7.1.1.json

Bugfixes:
* #1997 Fixed an issue causing a 502 gateway timeout to be thrown when you logged in.

Release v7.1.1 - Fixed gateway timeout issue when logging in

---

app/Http/Controllers/MDTImportController.php
app/Models/Floor/Floor.php
app/Providers/KeystoneGuruServiceProvider.php
app/Service/MDT/MDTImportStringService.php
app/Service/MDT/MDTMappingImportService.php
app/Service/SimulationCraft/RaidEventsService.php
database/seeders/SeasonsSeeder.php
database/seeders/releases/v7.4.1.json

Bugfixes:
* #2079 Fixed various crashes and issues that were introduced in release v7.4.

Release v7.4.1 - Hotfixes for v7.4 release

---

app/Console/Commands/Scheduler/RefreshOutdatedThumbnails.php
app/Http/Controllers/DungeonRouteController.php
database/seeders/releases/v7.4.7.json
resources/assets/js/custom/enemyvisuals/enemyvisualmanager.js
resources/views/common/thirdparty/adfooter.blade.php

Bugfixes:
* #2093 Route thumbnail generation now works again.

Release v7.4.7 - Route thumbnail generation is working again

---

app/Logic/Structs/IngameXY.php
app/Providers/LoggingServiceProvider.php
app/Service/Coordinates/CoordinatesService.php
app/Service/MDT/Logging/MDTImportStringServiceLogging.php
app/Service/MDT/Logging/MDTImportStringServiceLoggingInterface.php
app/Service/MDT/MDTBaseService.php
app/Service/MDT/MDTImportStringService.php
database/seeders/releases/v10.0.3.json
lang/en_US/logic.php

MDT Importer changes:
* #2379 Improved logging for importing MDT strings so I can debug issues that crop up.

Release v10.0.3 - Improved logging for importing MDT strings

---

app/Exceptions/Handler.php
app/Exceptions/Logging/HandlerLogging.php
app/Exceptions/Logging/HandlerLoggingInterface.php
app/Http/Controllers/Ajax/AjaxUserController.php
app/Http/Controllers/MDTImportController.php
app/Logic/Datatables/ColumnHandler/DatatablesColumnHandler.php
app/Logic/Datatables/ColumnHandler/DungeonRoutes/AuthorNameColumnHandler.php
app/Logic/Datatables/ColumnHandler/DungeonRoutes/DungeonColumnHandler.php
app/Logic/Datatables/ColumnHandler/DungeonRoutes/DungeonRouteAffixesColumnHandler.php
app/Logic/Datatables/ColumnHandler/DungeonRoutes/DungeonRouteAttributesColumnHandler.php
app/Logic/Datatables/ColumnHandler/DungeonRoutes/EnemyForcesColumnHandler.php
app/Logic/Datatables/ColumnHandler/DungeonRoutes/RatingColumnHandler.php
app/Logic/Datatables/ColumnHandler/DungeonRoutes/ViewsColumnHandler.php
app/Logic/Datatables/ColumnHandler/SimpleColumnHandler.php
app/Logic/Datatables/ColumnHandler/Users/IdColumnHandler.php
app/Logic/Datatables/DatatablesHandler.php
app/Providers/AppServiceProvider.php
app/Providers/LoggingServiceProvider.php
app/Providers/RouteServiceProvider.php
config/laravel-model-caching.php
database/seeders/releases/v11.7.1.json
resources/assets/css/map.css
resources/assets/js/custom/dungeonmap.js
resources/views/common/maps/map.blade.php

Bugfixes:
* #2618 Admin-only coordinate controls no longer show up for everyone, whoops!
* #2619 It is no longer possible to create permanent routes while not logged in by editing the request done to the server.
* #2613 Temporarily disabled rate limiting while investigating why it gets triggered so often.

Release v11.7.1 - Rate limiting updates, more bugfixes

---

app/Service/RaiderIO/Dtos/HeatmapDataFilter.php
database/seeders/releases/v11.9.8.json
resources/views/common/maps/controls/heatmapsearch.blade.php

Heatmap changes:
* #2690 Added region filter.

Release v11.9.8 - Region filter for heatmaps

---

app/Models/Dungeon.php
app/Service/RaiderIO/Dtos/HeatmapDataFilter.php
database/seeders/releases/v12.1.1.json
resources/assets/js/custom/constants.js
resources/assets/js/custom/inline/common/maps/heatmapsearchsidebar.js
resources/assets/js/custom/statemanager.js
resources/views/app/release/discord.blade.php
resources/views/app/release/discord_footer.blade.php
resources/views/app/release/reddit.blade.php
resources/views/common/maps/map.blade.php

Bugfixes:
* #2721 minSamplesRequired is no longer rendered for non-admins.

Release v12.1.1 - Fixed minSamplesRequired

---

app/Service/AffixGroup/AffixGroupEaseTierService.php
app/Service/Cache/CacheService.php
app/Service/Cache/Logging/CacheServiceLogging.php
app/Service/Cache/Logging/CacheServiceLoggingInterface.php

… of uselessness if there's a bit of load on the system

Release v13.0.3 v5

---

app/Http/Requests/Heatmap/ExploreUrlFormRequest.php
app/Service/RaiderIO/Dtos/HeatmapDataFilter.php
database/seeders/releases/v13.0.12.json
resources/assets/js/custom/inline/common/maps/heatmapsearchsidebar.js

Heatmap changes:
* #2812 Preparation for allowing to filter by many more spells than just Bloodlust.

Release v13.0.12

---

app/Service/View/ViewService.php
config/database.php
config/laravel-model-caching.php
database/seeders/releases/v13.4.2.json
docker-compose/app-aws/Dockerfile
docker-compose/cron-aws/Dockerfile
docker-compose/laravel-echo-server-aws/Dockerfile

General changes:
* #2838 Various other fixes to make AWS deployment possible.

Release v13.4.2 - More hotfixes for AWS deployment

---

app/Repositories/Database/DungeonRoute/DungeonRouteRepository.php
app/Repositories/Interfaces/DungeonRoute/DungeonRouteRepositoryInterface.php
app/Repositories/Stub/DungeonRoute/DungeonRouteRepository.php
app/Service/DungeonRoute/DungeonRouteService.php
app/Service/DungeonRoute/Logging/DungeonRouteServiceLogging.php
app/Service/DungeonRoute/Logging/DungeonRouteServiceLoggingInterface.php
app/Service/DungeonRoute/Logging/ThumbnailServiceLogging.php
app/Service/DungeonRoute/Logging/ThumbnailServiceLoggingInterface.php
app/Service/DungeonRoute/ThumbnailService.php
database/seeders/releases/v13.4.4.json
docker-compose/cron-aws/etc/cron.d/scheduler
docker-compose/laravel-echo-server/bin/setup-env.sh
docker-compose/laravel-echo-server/src/laravel-echo-server-template.json
resources/assets/css/map.css
resources/views/layouts/sitepage.blade.php

General changes:
* #2838 Many more changes for AWS deployment

Release v13.4.4 - Even even more fixes for AWS deployment

---

app/Console/Kernel.php
app/Http/Middleware/ReadOnlyMode.php
app/Providers/AppServiceProvider.php
config/logging.php
database/seeders/releases/v13.4.7.json
docker-compose/app-aws/Dockerfile
docker-compose/app-aws/usr/local/etc/php-fpm.d/zz-overrides.conf
docker-compose/app/Dockerfile
docker-compose/app/usr/local/etc/php-fpm.d/zz.log.conf
docker-compose/cron-aws/etc/cron.d/scheduler
docker-compose/cron/etc/cron.d/scheduler
docker-compose/nginx/keystone.guru.conf

Bugfixes:
* #2838 php-fpm should no longer run out of resources and take the site down.

Release v13.4.7 - Fixed site going down after some time.

---

database/seeders/releases/v13.8.7.json
resources/assets/css/map.css
resources/assets/js/custom/inline/common/maps/heatmapsearchsidebar.js
resources/assets/js/custom/inline/common/search/filters/filterimageselect.js
resources/assets/js/custom/inline/common/search/filters/filterimageselectdungeons.js
resources/assets/js/custom/inline/common/search/filters/filterinputweeklyaffixgroups.js
resources/assets/js/custom/inline/common/search/filters/filterradio.js
resources/assets/js/custom/inline/common/search/filters/filterselect.js
resources/assets/js/custom/inline/common/search/filters/filterselectclasses.js
resources/assets/js/custom/inline/common/search/filters/filterselectclassesplayerdeaths.js
resources/assets/js/custom/inline/common/search/filters/filterselectspecializations.js
resources/assets/js/custom/inline/common/search/filters/filterselectspecializationsplayerdeaths.js

Heatmap changes:
* #2951 Final changes to prevent embedded heatmaps from stealing focus (pass showSidebar=0). Let's hope it's truly the final fixes now!

Release v13.8.7 - Final fixes for embedded heatmaps stealing focus
